### ISSUE TITLE
No funciona el espejo

### ISSUE THREAD

**Issue by henot777** [BlenderNPR/Abnormal#2]
No funciona la opción de espejo y el movimiento en el entorno
![Sin-título-1](https://user-images.githubusercontent.com/64385187/80323095-3d19e300-87f7-11ea-840e-0784faf2329d.gif)

**Comment by CodyWinch** [comment]
2 possible things going wrong here.
1 - your objects transforms are not zeroed out and the mirroring works in world space. I just uploaded a fix so that it works in local space.
2 - your objects origin is not a the center of the character and it can't be properly mirrored.

Try the new local space mirroring and see if that fixes it. If not I need more information on your object to diagnose further.
